# Generated by Django 5.0.7 on 2024-07-23 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, unique=True)),
                ('company', models.TextField(max_length=240)),
                ('role', models.CharField(max_length=240)),
                ('active', models.BooleanField(default=True)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, unique=True)),
                ('description', models.TextField(max_length=240)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('duration', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Done', 'Done')], default='Ongoing', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='emp_det.employee')),
            ],
        ),
    ]
