# Generated by Django 5.0.7 on 2024-07-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_det', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
