# Generated by Django 5.0.7 on 2024-07-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_det', '0003_address_employee_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='state',
        ),
    ]
