# Generated by Django 5.0.7 on 2024-07-29 05:10

import emp_det.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_det', '0004_remove_employee_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.JSONField(),
        ),
    ]
