# Generated by Django 5.0.7 on 2024-07-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_det', '0007_alter_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.JSONField(default=list),
        ),
    ]
